name: Deploy Nginx to Minikube

on:
  push:
    branches: ["main"] #push to main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify kubectl version
        run: kubectl version --client

      - name: Verify cluster access
        run: kubectl cluster-info

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s-manifests/

      - name: Check running pods
        run: kubectl get pods -o wide
